name: starfish
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  dio_cookie_manager: ^3.1.1
  web_socket_channel: ^3.0.1
  oktoast: ^3.4.0
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  flutter_swiper_view: ^1.1.8
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.0.0
  flutter_html: ^2.1.2
  pull_to_refresh: ^2.0.0
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  flustars: ^2.0.1
  dio: ^5.7.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
